[package]
name = "bank_account"
version = "0.1.0"
authors = ["Alexander.Mair@academytrainee.com <Alexander.Mair@academytrainee.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
